version: "3.2"

services:
  db_server:
    image: 10.136.119.106:5000/db
    networks:
      - blog_network
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    volumes:
      - type: volume
        source: dbvol
        target: /data/db
      - type: volume
        source: dbvol
        target: /data/configuredb
  
  app_server:
    image: 10.136.119.106:5000/app
    networks:
      - blog_network
    depends_on:
      - db_server
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure
  
  web_server:
    image: 10.136.119.106:5000/web
    networks:
      - blog_network
    ports:
      - 80:80
    depends_on:
      - app_server
    deploy:
      replicas: 3
      restart_policy:
        condition: on-failure

networks:
  blog_network:
volumes:
  dbvol:
    driver: local
    driver_opts:
      type: "nfs"
      o: addr=10.136.119.106,rw,nolock
      device: ":/var/nfs/dbvol"

